### ISSUE TITLE
CT: event indexing failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#150]
May be related to some changes @samreid is making for other CT issues.  Assigning to make aware.
```
charges-and-fields : phet-io-tests
6 out of 7 tests passed. 1 failed.
SimTests: charges-and-fields: event indexing failed:
message index 0 should match order it appeared after linearization
    at phetioEventsListener (https://bayes.colorado.edu/continuous-testing/snapshot-1535580689763/phet-io-wrappers/js/tests/SimTests.js?bust=1535582340314:441:24)
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1535580689763/phet-io-wrappers/common/js/Client.js:256:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1535580689763/phet-io-wrappers/common/js/Client.js:316:13)


Approximately 8/29/2018, 4:11:29 PM
```

**Comment by zepumph** [comment]
See https://github.com/phetsims/phet-io-wrappers/issues/107 and https://github.com/phetsims/phet-io-wrappers/issues/97 for more details and issue tracking.

**Comment by samreid** [comment]
@zepumph is https://github.com/phetsims/phet-io/issues/1336 the root problem of this issue?

**Comment by zepumph** [comment]
Yes indeed. We have globals that emit their construction events before phet-io listeners are wired up. We need something like a "phetioEvents.launch" maybe we can work on this sometime soon (probably after Faradays Law)

**Comment by samreid** [comment]
On hold pending work in https://github.com/phetsims/phet-io/issues/1336

**Comment by zepumph** [comment]
This issue is very out of date. CT looks clean now.
