### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#155]
```
charges-and-fields : fuzz : require.js : run
Uncaught Error: Assertion failed: the second order correction is larger than the first
Error: Assertion failed: the second order correction is larger than the first
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/assert/js/assert.js:22:13)
    at ElectricPotentialLine.getNextPositionAlongEquipotentialWithElectricPotential (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/charges-and-fields/js/charges-and-fields/model/ElectricPotentialLine.js?bust=1543911881218:104:17)
    at ElectricPotentialLine.getEquipotentialPositionArray (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/charges-and-fields/js/charges-and-fields/model/ElectricPotentialLine.js?bust=1543911881218:194:45)
    at new ElectricPotentialLine (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/charges-and-fields/js/charges-and-fields/model/ElectricPotentialLine.js?bust=1543911881218:57:31)
    at ChargesAndFieldsModel.addElectricPotentialLine (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/charges-and-fields/js/charges-and-fields/model/ChargesAndFieldsModel.js?bust=1543911881218:606:35)
    at Emitter.listener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/charges-and-fields/js/charges-and-fields/view/ElectricPotentialSensorNode.js?bust=1543911881218:134:9)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/axon/js/Emitter.js?bust=1543911881218:194:53)
    at PushButtonModel.fire (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/sun/js/buttons/PushButtonModel.js?bust=1543911881218:155:25)
    at Array.downPropertyObserver (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/sun/js/buttons/PushButtonModel.js?bust=1543911881218:88:16)
    at Emitter.emit3 (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/axon/js/Emitter.js?bust=1543911881218:265:52)
id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
charges-and-fields : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543906860197:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543906860197:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.voltageCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543906860197:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543906860197:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.gridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543906860197:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.snapToGridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543906860197:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
charges-and-fields : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543916193259:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543916193259:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.voltageCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543916193259:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543916193259:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.gridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543916193259:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.snapToGridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543916193259:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
charges-and-fields : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543935107498:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543935107498:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.voltageCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543935107498:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543935107498:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.gridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543935107498:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.snapToGridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543935107498:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
charges-and-fields : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910018243:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910018243:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.voltageCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910018243:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910018243:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.gridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910018243:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.snapToGridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910018243:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
charges-and-fields : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.electricFieldCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928393595:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.directionOnlyCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928393595:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.voltageCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928393595:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.valuesCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928393595:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.gridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928393595:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: charges-and-fields: iframe api failed:
phetioDocumentation expected for chargesAndFields.chargesAndFieldsScreen.view.controlPanel.snapToGridCheckbox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543928393595:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
```

**Comment by zepumph** [comment]
This is no longer a problem
