### ISSUE TITLE
CT: cannot read property toStateObject and phetio type passed to Property must be specified

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#159]
```
charges-and-fields : fuzz : built-phet-io : run
Query: fuzz&memoryLimit=1000&phetioStandalone
Uncaught TypeError: Cannot read property 'toStateObject' of undefined
TypeError: Cannot read property 'toStateObject' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:38374
    at e.phetioStartEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:30450)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:38295)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:38215)
    at e.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:37814)
    at Object.down (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:786879)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:1022786)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:1022985)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:1022527)
    at t.value (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329-phet-io/charges-and-fields/build/phet-io/charges-and-fields_all_phet-io.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&fuzz&memoryLimit=1000&phetioStandalone:1010:1021395)
id: Bayes Chrome
Approximately 3/7/2019, 5:36:14 AM
charges-and-fields : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: chargesAndFields.chargesAndFieldsScreen.model.electricPotentialSensor.positionProperty
Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: chargesAndFields.chargesAndFieldsScreen.model.electricPotentialSensor.positionProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/assert/js/assert.js:22:13)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/axon/js/Property.js?bust=1551964169545:92:78)
    at new ElectricPotentialSensor (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/charges-and-fields/js/charges-and-fields/model/ElectricPotentialSensor.js?bust=1551964169545:30:29)
    at new ChargesAndFieldsModel (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/charges-and-fields/js/charges-and-fields/model/ChargesAndFieldsModel.js?bust=1551964169545:157:36)
    at ChargesAndFieldsScreen.createModel (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/charges-and-fields/js/charges-and-fields/ChargesAndFieldsScreen.js?bust=1551964169545:30:16)
    at ChargesAndFieldsScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/joist/js/Screen.js?bust=1551964169545:249:26)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/joist/js/Sim.js?bust=1551964169545:785:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/joist/js/Sim.js?bust=1551964169545:796:27
id: Bayes Chrome
Approximately 3/7/2019, 5:36:14 AM
charges-and-fields : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: chargesAndFields.chargesAndFieldsScreen.model.electricPotentialSensor.positionProperty
Error: Assertion failed: phetioType passed to Property must be specified. Tandem.phetioID: chargesAndFields.chargesAndFieldsScreen.model.electricPotentialSensor.positionProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/assert/js/assert.js:22:13)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/axon/js/Property.js?bust=1551964169545:92:78)
    at new ElectricPotentialSensor (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/charges-and-fields/js/charges-and-fields/model/ElectricPotentialSensor.js?bust=1551964169545:30:29)
    at new ChargesAndFieldsModel (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/charges-and-fields/js/charges-and-fields/model/ChargesAndFieldsModel.js?bust=1551964169545:157:36)
    at ChargesAndFieldsScreen.createModel (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/charges-and-fields/js/charges-and-fields/ChargesAndFieldsScreen.js?bust=1551964169545:30:16)
    at ChargesAndFieldsScreen.initializeModel (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/joist/js/Screen.js?bust=1551964169545:249:26)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/joist/js/Sim.js?bust=1551964169545:785:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1551962174329/joist/js/Sim.js?bust=1551964169545:796:27
id: Bayes Chrome
Approximately 3/7/2019, 5:36:14 AM
charges-and-fields : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 3/7/2019, 5:36:14 AM
charges-and-fields : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 3/7/2019, 5:36:14 AM
```

**Comment by zepumph** [comment]
This has been fixed. Closing
