### ISSUE TITLE
CT: phetioID already registered

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#160]
```
charges-and-fields : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: chargesAndFields.chargesAndFieldsScreen.view.element_2.visibleProperty
Error: Assertion failed: phetioID already registered: chargesAndFields.chargesAndFieldsScreen.view.element_2.visibleProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/phet-io/js/phetioEngine.js?bust=1553172964561:333:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/phet-io/js/phetioEngine.js?bust=1553172964561:420:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/tandem/js/Tandem.js?bust=1553172964561:126:40)
    at NodeProperty.register (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/tandem/js/PhetioObject.js?bust=1553172964561:279:19)
    at NodeProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/tandem/js/PhetioObject.js?bust=1553172964561:232:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/tandem/js/PhetioObject.js?bust=1553172964561:126:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/axon/js/Property.js?bust=1553172964561:71:7)
    at new NodeProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/scenery/js/util/NodeProperty.js?bust=1553172964561:31:7)
    at new NodeIO (https://bayes.colorado.edu/continuous-testing/snapshot-1553169395079/scenery/js/nodes/NodeIO.js?bust=1553172964561:33:27)
id: Bayes Chrome
Approximately 3/21/2019, 5:56:35 AM
charges-and-fields : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 3/21/2019, 5:56:35 AM
```

**Comment by KatieWoe** [comment]
```
charges-and-fields : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: chargesAndFields.chargesAndFieldsScreen.view.element_0.visibleProperty
Error: Assertion failed: phetioID already registered: chargesAndFields.chargesAndFieldsScreen.view.element_0.visibleProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/phet-io/js/phetioEngine.js?bust=1553625785109:333:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/phet-io/js/phetioEngine.js?bust=1553625785109:420:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/Tandem.js?bust=1553625785109:126:40)
    at NodeProperty.register (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/PhetioObject.js?bust=1553625785109:291:19)
    at NodeProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/PhetioObject.js?bust=1553625785109:278:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/PhetioObject.js?bust=1553625785109:129:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/axon/js/Property.js?bust=1553625785109:70:7)
    at new NodeProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/scenery/js/util/NodeProperty.js?bust=1553625785109:31:7)
    at new NodeIO (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/scenery/js/nodes/NodeIO.js?bust=1553625785109:33:27)
id: Bayes Chrome
Approximately 3/26/2019, 12:09:41 PM
charges-and-fields : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: phetioID already registered: chargesAndFields.chargesAndFieldsScreen.view.element_0.visibleProperty
Error: Assertion failed: phetioID already registered: chargesAndFields.chargesAndFieldsScreen.view.element_0.visibleProperty
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/assert/js/assert.js:22:13)
    at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/phet-io/js/phetioEngine.js?bust=1553625785109:333:36)
    at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/phet-io/js/phetioEngine.js?bust=1553625785109:420:51)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/Tandem.js?bust=1553625785109:126:40)
    at NodeProperty.register (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/PhetioObject.js?bust=1553625785109:291:19)
    at NodeProperty.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/PhetioObject.js?bust=1553625785109:278:12)
    at new PhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/tandem/js/PhetioObject.js?bust=1553625785109:129:12)
    at new Property (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/axon/js/Property.js?bust=1553625785109:70:7)
    at new NodeProperty (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/scenery/js/util/NodeProperty.js?bust=1553625785109:31:7)
    at new NodeIO (https://bayes.colorado.edu/continuous-testing/snapshot-1553623781876/scenery/js/nodes/NodeIO.js?bust=1553625785109:33:27)
id: Bayes Chrome
Approximately 3/26/2019, 12:09:41 PM
```

**Comment by samreid** [comment]
The commit fixes this problem on my working copy.  Self-assigning to check bayes in a few columns.

**Comment by samreid** [comment]
CT hasn't shown this problem for many columns, closing.
