### ISSUE TITLE
CT cannot add the same listener twice

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#192]
```
charges-and-fields : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/charges-and-fields/charges-and-fields_en.html?continuousTest=%7B%22test%22%3A%5B%22charges-and-fields%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614318300362%22%2C%22timestamp%22%3A1614329202346%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/assert/js/assert.js:25:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:114:15)
at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Property.js:400:25)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:307:79
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:64:19)
at Proxy.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/createObservableArray.js:274:32)
at FireListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:697:23)
id: Bayes Chrome
Snapshot from 2/25/2021, 10:45:00 PM

----------------------------------

charges-and-fields : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/charges-and-fields/charges-and-fields_en.html?continuousTest=%7B%22test%22%3A%5B%22charges-and-fields%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1614318300362%22%2C%22timestamp%22%3A1614342956642%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/assert/js/assert.js:25:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:114:15)
at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Property.js:400:25)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:307:79
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:64:19)
at Proxy.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/createObservableArray.js:274:32)
at FireListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:697:23)
id: Bayes Chrome
Snapshot from 2/25/2021, 10:45:00 PM

----------------------------------

charges-and-fields : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/charges-and-fields/charges-and-fields_en.html?continuousTest=%7B%22test%22%3A%5B%22charges-and-fields%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614318300362%22%2C%22timestamp%22%3A1614325004577%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/assert/js/assert.js:25:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:114:15)
at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Property.js:400:25)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:307:79
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:64:19)
at Proxy.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/createObservableArray.js:274:32)
at FireListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:697:23)
id: Bayes Chrome
Snapshot from 2/25/2021, 10:45:00 PM

----------------------------------

charges-and-fields : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/charges-and-fields/charges-and-fields_en.html?continuousTest=%7B%22test%22%3A%5B%22charges-and-fields%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1614318300362%22%2C%22timestamp%22%3A1614343320198%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/assert/js/assert.js:25:13)
at TinyEmitter.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:114:15)
at BooleanProperty.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Property.js:400:25)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:307:79
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/TinyEmitter.js:86:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:39:29
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Action.js:225:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/Emitter.js:64:19)
at Proxy.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/axon/js/createObservableArray.js:274:32)
at FireListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1614318300362/scenery/js/listeners/PressListener.js:697:23)
id: Bayes Chrome
Snapshot from 2/25/2021, 10:45:00 PM
```

**Comment by jonathanolson** [comment]
I believe this was fixed by the recent common-code revert.
