### ISSUE TITLE
CT Trying to translate with a non-finite Vector2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/charges-and-fields#196]
```
charges-and-fields : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/charges-and-fields/charges-and-fields_en.html?continuousTest=%7B%22test%22%3A%5B%22charges-and-fields%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1647595636252%22%2C%22timestamp%22%3A1647598828271%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Trying to translate with a non-finite Vector2
Error: Assertion failed: Trying to translate with a non-finite Vector2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/assert/js/assert.js:25:13)
at AnimatedPanZoomListener.animateToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:898:19)
at AnimatedPanZoomListener.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/scenery/js/listeners/AnimatedPanZoomListener.js:202:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:267:43
at PhetioAction.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/tandem/js/PhetioAction.js:90:17)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:822:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:811:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1647595636252/chipper/dist/js/joist/js/Sim.js:789:12)
id: Bayes Chrome
Snapshot from 3/18/2022, 3:27:16 AM
```

**Comment by jessegreenberg** [comment]
This is a new assertion added trying to get more information from https://github.com/phetsims/charges-and-fields/issues/195. Closing that issue and moving over here since this is what CT will be reporting now. This is in my court.

**Comment by jessegreenberg** [comment]
From #195, I saw this once after fuzzing for ~30 minutes but haven't been able to see it since.

**Comment by KatieWoe** [comment]
This seems to happening in a few other sims on CT

**Comment by jessegreenberg** [comment]
Over slack @KatieWoe mentioned she saw this in estimation and equality-explorer as well so far.

**Comment by jessegreenberg** [comment]
I fuzzed charges-and-fields, estimation, and equality-explorer for 20 minutes and havent seen this issue yet.

**Comment by KatieWoe** [comment]
They seem to be happening in the pan-and-zoom fuzz test if that helps

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, yes I am running with the same query parameters as shown in the original issue
`brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true`

**Comment by jessegreenberg** [comment]
I found a potential case where the translation vector can have undefined x and y values and addressed it in the above commit. I am not sure if that is the case causing this though since I haven't been able to reproduce. Will continue to watch over the next several days.

**Comment by jessegreenberg** [comment]
This showed up again this morning in fractions-intro. But it hasn't shown up again in charges-and-fields. Moving to scenery.
